// Search component
export const FETCH_MOVIES_BY_QUERY_START = 'FETCH_MOVIES_BY_QUERY_START';
export const FETCH_MOVIES_BY_QUERY_SUCCESS = 'FETCH_MOVIES_BY_QUERY_SUCCESS';
export const FETCH_MOVIES_BY_QUERY_ERROR = 'FETCH_MOVIES_BY_QUERY_ERROR';
export const SAVE_URL_PARAMS = 'SAVE_URL_PARAMS';

// MovieDetails compomonent
export const FETCH_MOVIE_BY_ID_START = 'FETCH_MOVIE_BY_ID_START';
export const FETCH_MOVIE_BY_ID_SUCCESS = 'FETCH_MOVIE_BY_ID_SUCCESS';
export const FETCH_MOVIE_BY_ID_ERROR = 'FETCH_MOVIE_BY_ID_ERROR';

// Slider component
export const FETCH_SLIDE_MOVIE_DATA_START = 'FETCH_SLIDE_MOVIE_DATA_START';
export const FETCH_SLIDE_MOVIE_DATA_SUCCESS = 'FETCH_SLIDE_MOVIE_DATA_SUCCESS';
export const FETCH_SLIDE_MOVIE_DATA_ERROR = 'FETCH_SLIDE_MOVIE_DATA_ERROR';
export const SAVE_CUURENT_SLIDE_IDX = 'SAVE_CUURENT_SLIDE_IDX';
