export const FETCH_MOVIES_BY_QUERY_START = 'FETCH_MOVIES_BY_QUERY_START';
export const FETCH_MOVIES_BY_QUERY_SUCCESS = 'FETCH_MOVIES_BY_QUERY_SUCCESS';
export const FETCH_MOVIES_BY_QUERY_ERROR = 'FETCH_MOVIES_BY_QUERY_ERROR';
